# Generated by Django 4.0.2 on 2022-03-02 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Types',
                'db_table': 't_contract_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='educationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'db_table': 't_education_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='Language code', max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 't_language',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experience Level',
                'verbose_name_plural': 'Experience Levels',
                'db_table': 't_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.CharField(max_length=300)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('is_your_main', models.BooleanField(default=False)),
                ('updated_at', models.DateField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.level')),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 't_profile',
                'ordering': ['inserted_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 't_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name or description', max_length=50)),
                ('code', models.CharField(help_text='Skill code', max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 't_skill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='socialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=300)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'db_table': 't_social_network',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_url', models.CharField(max_length=300)),
                ('short_comments', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.socialnetwork')),
            ],
            options={
                'verbose_name': 'Profile Social Link',
                'verbose_name_plural': 'Profile Social Links',
                'db_table': 't_profile_social_link',
                'ordering': ['inserted_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'verbose_name': 'Profile Skill',
                'verbose_name_plural': 'Profile Skills',
                'db_table': 't_profile_skill',
                'ordering': ['skill'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.CharField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('short_comments', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.contracttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.role')),
            ],
            options={
                'verbose_name': 'Profile Experience',
                'verbose_name_plural': 'Profile Experiences',
                'db_table': 't_profile_experience',
                'ordering': ['date_start'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_url', models.CharField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.educationlevel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Profile Education',
                'verbose_name_plural': 'Profile Education',
                'db_table': 't_profile_education',
                'ordering': ['date_start'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
