# Generated by Django 4.0.2 on 2022-03-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infocore', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=200, verbose_name='Title')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Institution Name')),
                ('institution_url', models.CharField(max_length=500, verbose_name='Institution/Course URL')),
                ('date_start', models.DateField(verbose_name='Start At')),
                ('date_end', models.DateField(verbose_name='End At')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course descriprion')),
                ('is_certification', models.BooleanField(default=False, verbose_name='Certification?')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.account', verbose_name='Account name')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.educationlevel', verbose_name='Education Level')),
            ],
            options={
                'verbose_name': 'Education ',
                'verbose_name_plural': 'Education',
                'db_table': 't_education',
                'ordering': ['-date_start'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='experienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Experience Category',
                'verbose_name_plural': 'Experience Categories',
                'db_table': 't_experience_category',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Experience Level',
                'verbose_name_plural': 'Experience Levels',
                'db_table': 't_level',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
                ('banner', models.CharField(max_length=300)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=False)),
                ('is_your_main', models.BooleanField(default=False)),
                ('updated_at', models.DateField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infocore.account')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.level')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.role')),
                ('tag', models.ManyToManyField(to='infocore.Tag')),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 't_profile',
                'ordering': ['-inserted_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.CharField(blank=True, max_length=300, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('short_comments', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.contracttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.role')),
            ],
            options={
                'verbose_name': 'Profile Experience',
                'verbose_name_plural': 'Profile Experiences',
                'db_table': 't_profile_experience',
                'ordering': ['-date_start'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_url', models.CharField(max_length=300)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.socialnetwork')),
            ],
            options={
                'verbose_name': 'Profile Social Link',
                'verbose_name_plural': 'Profile Social Links',
                'db_table': 't_profile_social_link',
                'ordering': ['inserted_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_sequence', models.CharField(default='1', max_length=20)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.skill')),
            ],
            options={
                'verbose_name': 'Profile Skill',
                'verbose_name_plural': 'Profile Skills',
                'db_table': 't_profile_skill',
                'ordering': ['skill_sequence'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileExperienceItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('experience_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.experiencecategory')),
                ('profile_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profileexperience')),
            ],
            options={
                'verbose_name': 'Profile Experience Item',
                'verbose_name_plural': 'Profile Experiences Itens',
                'db_table': 't_profile_experience_itens',
                'ordering': ['sequence'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='profileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('observations', models.CharField(max_length=300)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.education')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Profile Education',
                'verbose_name_plural': 'Profile Education',
                'db_table': 't_profile_educations',
                'ordering': ['sequence'],
                'managed': True,
            },
        ),
    ]
