# Generated by Django 4.0.2 on 2022-03-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infocore', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.account', verbose_name='Account'),
        ),
    ]
