# Generated by Django 4.0.2 on 2022-03-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profileskills_options_profileskills_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesociallinks',
            name='short_comments',
        ),
    ]
