# Generated by Django 4.0.2 on 2022-03-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_experiencecategory_profileexperienceitens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileexperience',
            name='company_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profileexperience',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
