# Generated by Django 4.0.2 on 2022-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profileexperience_company_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileexperience',
            options={'managed': True, 'ordering': ['-date_start'], 'verbose_name': 'Profile Experience', 'verbose_name_plural': 'Profile Experiences'},
        ),
        migrations.AddField(
            model_name='profileexperience',
            name='experience_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
