# Generated by Django 4.0.2 on 2022-03-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_title', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_url', models.CharField(max_length=300)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_certification', models.BooleanField(default=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.educationlevel')),
            ],
            options={
                'verbose_name': 'Education ',
                'verbose_name_plural': 'Education',
                'db_table': 't_education',
                'ordering': ['-date_start'],
                'managed': True,
            },
        ),
    ]
