# Generated by Django 4.0.2 on 2022-03-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttype',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Contract Type', 'verbose_name_plural': 'Contract Types'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Education Level', 'verbose_name_plural': 'Education Levels'},
        ),
        migrations.AlterModelOptions(
            name='experiencecategory',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Experience Category', 'verbose_name_plural': 'Experience Categories'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Experience Level', 'verbose_name_plural': 'Experience Levels'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True, 'ordering': ['-inserted_at'], 'verbose_name': 'Professional Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Social Network', 'verbose_name_plural': 'Social Networks'},
        ),
        migrations.AlterField(
            model_name='education',
            name='date_end',
            field=models.DateField(verbose_name='End At'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_start',
            field=models.DateField(verbose_name='Start At'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Course Descriprion'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.educationlevel', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(max_length=200, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_url',
            field=models.CharField(max_length=500, verbose_name='Course URL'),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_certification',
            field=models.BooleanField(default=False, verbose_name='Certification?'),
        ),
    ]
