# Generated by Django 4.0.2 on 2022-03-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_skillcategory_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='profiles.skillcategory', verbose_name='Skill Category'),
        ),
    ]
