# Generated by Django 4.0.2 on 2022-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_skill_skill_category_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
