# Generated by Django 4.0.2 on 2022-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_account_is_active_account_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
