# Generated by Django 4.0.2 on 2022-03-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 't_tags',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Tag'),
        ),
    ]
