# Generated by Django 4.0.2 on 2022-03-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infocore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lead Name')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Phone')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lead Description')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infocore.role', verbose_name='Role')),
                ('skill', models.ManyToManyField(to='infocore.Skill')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 't_lead',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='leadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Activity')),
                ('activity_date', models.DateField(verbose_name='Activity Date')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lead Description')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('action_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detail')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Activities',
                'verbose_name_plural': 'Lead Activity',
                'db_table': 't_lead_activity',
                'ordering': ['-activity_date'],
                'managed': True,
            },
        ),
    ]
