# Generated by Django 4.0.2 on 2022-03-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lead Name')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lead Description')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 't_lead',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
