# Generated by Django 4.0.2 on 2022-03-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infocore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name or description')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Link Type',
                'verbose_name_plural': 'Link Types',
                'db_table': 't_link_type',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('project_url', models.CharField(max_length=500, verbose_name='Main Project URL')),
                ('start_date', models.DateField(verbose_name='Start At')),
                ('end_date', models.DateField(verbose_name='Ended At')),
                ('budget_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project descriprion')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Expected Goals')),
                ('is_deleted', models.BooleanField(default=False)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.businessarea', verbose_name='Business Area')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocore.industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 't_project',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='projectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name or description')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Project Status',
                'db_table': 't_project_status',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='projectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Module Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Module descriprion')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Module',
                'verbose_name_plural': 'Project Modules',
                'db_table': 't_project_module',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectstatus', verbose_name='Project Status'),
        ),
    ]
