# Generated by Django 4.0.2 on 2022-03-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_businessarea_industry_linktype_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('project_url', models.CharField(max_length=500, verbose_name='Main Project URL')),
                ('start_date', models.DateField(verbose_name='Start At')),
                ('end_date', models.DateField(verbose_name='Ended At')),
                ('budget_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project descriprion')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Expected Goals')),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.businessarea', verbose_name='Business Area')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 't_project',
                'ordering': ['-start_date'],
                'managed': True,
            },
        ),
    ]
