# Generated by Django 4.0.2 on 2022-03-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectstatus', verbose_name='Project Status'),
            preserve_default=False,
        ),
    ]
